[versions]

androidCompileSdk = "33"
androidMinSdk = "21"
androidTargetSdk = "33"

androidGradlePlugin = "7.4.2"
kotlin = "1.8.10"

composeBom = "2023.04.00"
composeCompiler = "1.4.3"

[libraries]

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.0"
androidx-lifecycle-viewmodelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1"

junit = "junit:junit:4.13.2"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"

sd-aligner = "com.github.zj565061763:aligner:1.0.0"
sd-composeSystemui = "com.github.zj565061763:compose-systemui:1.0.0-beta03"

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
